#route.yml

- pattern: /{language:[a-z]{2}}/event/fire
  method: POST
  option:
    controller: Event
    action: fire

- pattern: /{language:[a-z]{2}}/event/get/{service}/{method}
  method: GET
  option:
    controller: Event
    action: get

- pattern: /{language:[a-z]{2}}/event/query/{service}/{method}
  method: GET
  option:
    controller: Event
    action: query

- pattern: /{language:[a-z]{2}}/event/{service}/{method}
  method: POST
  option:
    controller: Event
    action: post

- pattern: /{language:[a-z]{2}}/event/{service}/{method}
  method: PUT
  option:
    controller: Event
    action: put

- pattern: /{language:[a-z]{2}}/event/{service}/{method}
  method: DELETE
  option:
    controller: Event
    action: delete
